### http://localhost:4015/

## Passenger API Endpoints

### Join passenger to the queue
POST http://localhost:4015/api/passenger/join

### Leave passenger from the queue
POST http://localhost:4015/api/passenger/leave

### Get passenger queue length
GET http://localhost:4015/api/passenger/queue

###
### Taxi API Endpoints
###

### Join taxi to the queue
POST http://localhost:4015/api/taxi/join

### Depart taxi from the queue
POST http://localhost:4015/api/taxi/depart

### Get taxi queue length
GET http://localhost:4015/api/taxi/queue